restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    toggle_assign_to_dish,
    CookCreateView,
    CookDeleteView,
    no_permission,
    IngredientListView,
    IngredientUpdateView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientDetailView,
    CookUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("login/", index, name="index"),
    path(
        "categories/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "categories/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "categories/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "categories/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "cars/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list",
    ),
    path(
        "ingredients/<int:pk>/",
        IngredientDetailView.as_view(),
        name="ingredient-detail",
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("no_permission/", no_permission, name="no_permission"),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="btn btn-outline-primary">prev</a>
      </li>
    {% endif %}
    <li class="page-item default">
      <span class="page-link text-dark bg-default">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="btn btn-outline-primary">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-outline-primary search-btn" type="submit" value="Search">
</form>

templates/includes/sidebar.html
<!-- Navbar -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="btn btn-dark px-3" href="{% url 'restaurant:index' %}" role="button" >
      <i class="fas fa-home"></i>
    </a>
      <div class="d-flex align-items-center">
      {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-link px-3 me-2">Logout</a>
          <a href="{{ user.get_absolute_url }}" class="btn btn-primary me-3">{{ user.get_username }}</a>
          <a class="btn btn-dark px-3" href="https://github.com/wQuelS/restaurant-kitchen-service/tree/develop" role="button">
            <i class="fab fa-github"></i>
          </a>
      {% else %}
        <a href="{% url 'login' %}" class="btn btn-link px-3 me-2">Login</a>
        <a href="#" class="btn btn-primary me-3">Sign up</a>
      {% endif %}
      </div>
    </div>

</nav>

templates/includes/topnav.html
<!-- Navbar -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="btn btn-dark px-3" href="{% url 'restaurant:index' %}" role="button" >
      <i class="fas fa-home"></i>
    </a>

    <div class="d-flex align-items-center">
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn btn-link px-3 me-2">Logout</a>
        <a href="{{ user.get_absolute_url }}" class="btn btn-primary me-3">{{ user.get_username }}</a>
        <a class="btn btn-dark px-3" href="https://github.com/wQuelS/restaurant-kitchen-service/tree/develop" role="button">
          <i class="fab fa-github"></i>
        </a>
    {% else %}
      <a href="{% url 'login' %}" class="btn btn-link px-3 me-2">Login</a>
      <a href="{% url 'restaurant:cook-create' %}" class="btn btn-primary me-3">Sign up</a>
    {% endif %}
    </div>
  </div>

</nav>