restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    toggle_assign_to_dish,
    CookCreateView,
    CookDeleteView,
    no_permission,
    IngredientListView,
    IngredientUpdateView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientDetailView,
    CookUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("login/", index, name="index"),
    path(
        "categories/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "categories/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail",
    ),
    path(
        "categories/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "categories/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "cars/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list",
    ),
    path(
        "ingredients/<int:pk>/",
        IngredientDetailView.as_view(),
        name="ingredient-detail",
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("no_permission/", no_permission, name="no_permission"),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="dishes"
    )

    class Meta:
        ordering = ["id"]
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        ordering = ["username"]
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    dishes = models.ManyToManyField(
        Dish, related_name="ingredients", blank=True
    )

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import (
    RegexValidator,
    MinValueValidator,
    MaxValueValidator,
)

from restaurant.models import Dish, Ingredient


class CookFormMixin(forms.ModelForm):
    years_of_experience = forms.IntegerField(
        required=True,
        validators=[
            MinValueValidator(0, message="Should be between 0 and 50"),
            MaxValueValidator(50, message="Should be between 0 and 50"),
        ],
    )
    username = forms.CharField(
        required=True,
        validators=[
            RegexValidator(
                r"^[A-Za-z0-9_]+$",
                message="Username can contain only latin letters, numbers and '_' sign!",
            )
        ],
    )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class IngredientForm(forms.ModelForm):
    dishes = forms.ModelMultipleChoiceField(
        queryset=Dish.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Ingredient
        fields = "__all__"


class CookCreationForm(CookFormMixin, UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search..."}),
    )

restaurant/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from restaurant.forms import (
    DishForm,
    CookCreationForm,
    CookUpdateForm,
    SearchForm,
    IngredientForm,
)
from restaurant.models import Dish, DishType, Cook, Ingredient


@login_required
def index(request):
    """View function for the home page of the site."""

    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1,
    }

    return render(request, "restaurant/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_list.html"
    paginate_by = 5
    queryset = DishType.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("search", "")

        context["search_form"] = SearchForm(initial={"search": name})

        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["search"]
            )

        return self.queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_detail.html"
    queryset = DishType.objects.prefetch_related("dish_set")


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    template_name = "restaurant/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    template_name = "restaurant/dish_type_form.html"
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dish-type-list")
    template_name = "restaurant/dish_type_confirm_delete.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    context_object_name = "dish_list"
    template_name = "restaurant/dish_list.html"
    queryset = Dish.objects.select_related("dish_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("search", "")

        context["search_form"] = SearchForm(initial={"search": name})

        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["search"]
            )

        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = Cook.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("search", "")

        context["search_form"] = SearchForm(initial={"search": name})

        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["search"]
            )

        return self.queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("restaurant:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("restaurant:cook-list")

    def get_object(self, queryset=None):
        return self.request.user


@method_decorator(
    staff_member_required(login_url="/no_permission"), name="dispatch"
)
class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cook-list")


class IngredientListView(generic.ListView):
    model = Ingredient
    paginate_by = 5
    queryset = Ingredient.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("search", "")
        context["search_form"] = SearchForm(
            initial={
                "search": name,
            }
        )

        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["search"]
            )

        return self.queryset


class IngredientDetailView(generic.DetailView):
    model = Ingredient


class IngredientCreateView(generic.CreateView):
    model = Ingredient
    form_class = IngredientForm
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientUpdateView(generic.UpdateView):
    model = Ingredient
    form_class = IngredientForm
    success_url = reverse_lazy("restaurant:ingredient-list")


class IngredientDeleteView(generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("restaurant:ingredient-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if Dish.objects.get(id=pk) in cook.dishes.all():
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(
        reverse_lazy("restaurant:dish-detail", args=[pk])
    )


def no_permission(request):
    cook = Cook.objects.get(id=request.user.id)
    context = {
        "cook": cook,
    }
    return render(request, "restaurant/no_permission.html", context=context)

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</h1>
  <br>
  <p><i>Are you sure about this ?</i></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, Delete" class="btn btn-outline-danger">
    <a href="{% url 'restaurant:cook-list' %}" class = "btn btn-outline-secondary"> <i class="fa fa-ban" aria-hidden="true"></i> Cancel</a>
  </form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>
      {{ cook.username }}
      <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" role="button" class="btn btn-outline-danger float-right">
        <i class="fa fa-trash" aria-hidden="true"></i> Delete
      </a>

      <a href="{% url 'restaurant:cook-update' pk=cook.id %}" role="button" class="btn btn-outline-success float-right">
        <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
      </a>

  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {% if cook.is_staff %}<i class="fa-solid fa-check"></i>{% else %}<i class="fa-solid fa-xmark"></i>{% endif %}</p>
  <hr>

  <h4>Dishes: </h4>
  <table class="table table-hover table-striped">
    <thead>
      <tr class="tr-head">
        <th>Name</th>
        <th>Category</th>
        <th>ID</th>
      </tr>
    </thead>
    <tbody>
      {% for dish in cook.dishes.all %}
        <tr>
          <td><a href="{% url 'restaurant:dish-detail' pk=dish.id %}">{{ dish.name }}</a></td>
          <td><a href="{% url 'restaurant:dish-type-detail' pk=dish.dish_type.id %}">{{ dish.dish_type.name }}</a></td>
          <td>{{dish.id}}</td>
          <td></td>
        </tr>

      {% empty %}
        <p>No dishes!</p>
      {% endfor %}
  </table>
{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update Years of Experience,Create Cook Profile" }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-outline-success" style="margin-top: 10px">
  </form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends "base.html" %}
{% block content %}
  <h1>
    Our Team:
  <a href="{% url 'restaurant:cook-create' %}" class="float-right btn btn-outline-primary add-button">
      <i class="fa fa-plus-circle"></i> Add
  </a>
  </h1>

  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}

  <table class="table table-hover table-striped">
    <thead>
      <tr class="tr-head">
        <th>ID</th>
        <th>Name</th>
        <th>Username</th>
        <th>Amount of dishes</th>
        <th>Experience (years)</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
    {% if cook_list %}
      {% for cook in cook_list %}

        <tr>
              <td>
                {{ cook.id }}
              </td>
              <td>
                <a href="{% url 'restaurant:cook-detail' pk=cook.id %}">{{ cook.first_name }} {{ cook.last_name }}</a>
              </td>
              <td>
                {{  cook.username }} {% if user == cook %} (Me){% endif %}
              </td>
              <td>
                {{  cook.dishes.count }}
              </td>
              <td>
                {{  cook.years_of_experience }}
              </td>

                <td>
                  {% if request.user.username == cook.username or user.is_superuser %}
                    <a href="{% url 'restaurant:cook-update' pk=cook.id %}" role="button" class="btn btn-outline-success">
                      <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
                    </a>
                  {% else %}
                    <a href="{% url 'restaurant:no_permission' %}" role="button" class="btn btn-outline-success">
                      <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
                    </a>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" role="button" class="btn btn-outline-danger">
                    <i class="fa fa-trash" aria-hidden="true"></i> Delete
                  </a>
                </td>

          </tr>

      {% endfor %}
    {% else %}
      <p> There are no chiefs yet:(</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ object.name }}</h1>
  <br>
  <p><strong>Are you sure about this ?</strong></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, Delete" class="btn btn-outline-danger">
    <a href="{% url 'restaurant:dish-list' %}" class = "btn btn-outline-secondary"> <i class="fa fa-ban" aria-hidden="true"></i> Cancel</a>
  </form>
{% endblock %}

templates/restaurant/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ object.name }}</h1>
  <br>
  <p><i>Are you sure about this ?</i></p>
  <p><strong>This action will delete {{ object.dish_set.count }} dishes associated with this category</strong></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, Delete" class="btn btn-outline-danger">
    <a href="{% url 'restaurant:dish-type-list' %}" class = "btn btn-outline-secondary"> <i class="fa fa-ban" aria-hidden="true"></i> Cancel</a>
  </form>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}
{% block content %}
  <h1>
    Types of dish
    <a href="{% url 'restaurant:dish-type-create' %}" class="float-right btn btn-outline-primary add-button">
      <i class="fa fa-plus-circle"></i> Add
    </a>
  </h1>

  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}

  <table class="table table-hover table-striped">
    <thead>
      <tr class="tr-head">
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
    {% if dish_type_list%}
      {% for type in dish_type_list %}

        <tr>
              <td>
                {{ type.id }}
              </td>
              <td>
                <a href="{% url 'restaurant:dish-type-detail' pk=type.id %}">{{ type.name }}</a>
              </td>
              <td>
                <a href="{% url 'restaurant:dish-type-update' pk=type.id %}" role="button" class="btn btn-outline-success">
                  <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
                </a>
              </td>
              <td>
                <a href="{% url 'restaurant:dish-type-delete' pk=type.id %}" role="button" class="btn btn-outline-danger">
                  <i class="fa fa-trash" aria-hidden="true"></i> Delete
                </a>
              </td>
          </tr>

      {% endfor %}
    {% else %}
      <p> There is no dish types</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <main class="main-content">
    <div class="container div-content">
      <!--Section: Content-->
     <section class="text-center">

        <div class="row">
          <div class="col-lg-4 col-md-12">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img style="display: block; -webkit-user-select: none; margin: auto; cursor: zoom-in; background-color: hsl(0, 0%, 90%); transition: background-color 300ms;"
                     src="{% static 'images/chief.jpg' %}"  class="img-fluid">
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">Chiefs:</h5>
                <p class="card-text">
                  Amount of cooks: {{ num_cooks }}
                </p>
                <a href="{% url 'restaurant:cook-list' %}" class="btn btn-primary">View</a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img style="display: block; -webkit-user-select: none; margin: auto; cursor: zoom-in; background-color: hsl(0, 0%, 90%); transition: background-color 300ms;"
                     src="{% static 'images/food.jpeg' %}" class="img-fluid">
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">Dishes: </h5>
                <p class="card-text">
                  Total number of dishes: {{ num_dishes }}
                </p>
                <a href="{% url 'restaurant:dish-list' %}" class="btn btn-primary">View</a>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img src="{% static 'images/categories.jpg' %}" class="img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.55);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">Categories of dishes</h5>
                <p class="card-text">
                  Dishes by categories: {{ num_dish_types }}
                </p>
                <a href="{% url 'restaurant:dish-type-list' %}" class="btn btn-primary">View</a>
              </div>
            </div>
          </div>


        </div>
      </section>
    </div>
  <a href="{% url 'restaurant:ingredient-list' %}" class="btn btn-secondary">Ingredients</a>
    <hr>
  <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
  </main>
{% endblock %}

templates/restaurant/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete {{ ingredient.name }}</h1>
  <br>
  <p><i>Are you sure about this ?</i></p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes, Delete" class="btn btn-outline-danger">
    <a href="{% url 'restaurant:ingredient-list' %}" class = "btn btn-outline-secondary"> <i class="fa fa-ban" aria-hidden="true"></i> Cancel</a>
  </form>
{% endblock %}

templates/restaurant/ingredient_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dishes with {{ ingredient.name }}
    <a href="{% url 'restaurant:ingredient-delete' pk=ingredient.id %}" class="btn btn-outline-danger link-to-page float-right">
      <i class="fa fa-trash" aria-hidden="true"></i> Delete
    </a>

    <a href="{% url 'restaurant:ingredient-update' pk=ingredient.id %}" class="btn btn-outline-success link-to-page float-right">
      <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
    </a>
  </h1>
  <hr>
  <table class="table table-hover table-striped">
    <thead>
      <tr class="tr-head">
        <th>Name</th>
        <th>Category of dish</th>
        <th>Number of dishes</th>
      </tr>
    </thead>
    <tbody>
    {% if ingredient.dishes.all %}
      {% for dish in ingredient.dishes.all %}

        <tr>
          <td>
            <a href="{% url 'restaurant:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
          </td>
          <td>{{ dish.dish_type.name }}</td>
          <td>
            {{ dish.cooks.count }}
          </td>
        </tr>

      {% endfor %}
    {% else %}
      <p> There are no ingredients yet</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

templates/restaurant/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Ingredient</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    Ingredients
    <a href="{% url 'restaurant:ingredient-create' %}" class="float-right btn btn-outline-primary add-button">
      <i class="fa fa-plus-circle"></i> Add
    </a>
  </h1>

  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}

  <table class="table table-hover table-striped">
    <thead>
      <tr class="tr-head">
        <th>ID</th>
        <th>Name</th>
        <th>Number of dishes</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% if ingredient_list %}
      {% for item in ingredient_list %}

        <tr>
              <td>{{ item.id }}</td>
              <td>
                <a href="{% url 'restaurant:ingredient-detail' pk=item.id %}">{{ item.name }}</a>
              </td>
              <td>
                {{ item.dishes.count }}
              </td>
              <td>
                <a href="{% url 'restaurant:ingredient-update' pk=item.id %}" role="button" class="btn btn-outline-success">
                  <i class="fa fa-pencil-square" aria-hidden="true"></i> Update
                </a>
              </td>
              <td>
                <a href="{% url 'restaurant:ingredient-delete' pk=item.id %}" role="button" class="btn btn-outline-danger">
                  <i class="fa fa-trash" aria-hidden="true"></i> Delete
                </a>
              </td>
          </tr>

      {% endfor %}
    {% else %}
      <p> There is no dishes yet</p>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

templates/restaurant/no_permission.html
{% extends "base.html" %}

{% block content %}
  <h3 style="color: red">Oops, access denied. Seems like you don't have permission for this action.</h3>
  <a href="{% url 'restaurant:cook-list' %}"><i class="fa-sharp fa-solid fa-rotate-left"></i> Go back</a>
{% endblock %}